# Generated by Django 6.1.1 on 2026-09-23 07:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Укажите имя гостя')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Укажите номер телефона')),
                ('count_of_guests', models.PositiveIntegerField(default=1, verbose_name='Укажите количество гостей')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Укажите дату бронирования')),
                ('time', models.TimeField(default=datetime.time(0, 0), verbose_name='Укажите время бронирования')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.table', verbose_name='Выберите столик')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
            },
        ),
    ]
