# Generated by Django 6.1.1 on 2026-09-23 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tables.table', verbose_name='Выберите столик'),
        ),
    ]
