# Generated by Django 6.1.1 on 2026-09-23 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='table',
        ),
    ]
