# Generated by Django 6.1.1 on 2026-09-25 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_booking_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='confirmation',
            field=models.BooleanField(default=False, verbose_name='Подтверждение бронирования'),
        ),
    ]
