# Generated by Django 6.1.1 on 2026-09-25 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_booking_confirmation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'permissions': [('can_confirm_booking', 'Can unpublish product')], 'verbose_name': 'Бронирование', 'verbose_name_plural': 'Бронирования'},
        ),
    ]
