# Generated by Django 6.1.1 on 2026-09-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название стола')),
                ('count_of_seats', models.PositiveIntegerField(verbose_name='Количество посадочных мест')),
                ('is_reservation', models.BooleanField(default=False, verbose_name='Статус бронирования')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
            },
        ),
    ]
